# Site Settings
title: Moisés Jurado | My Resume
url: 'https://moisesjurado.github.io/'
#baseurl: '/online-cv' #change it according to your repository name #moises: aqui se pone un 'subdominio'

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Moisés Jurado
tagline: Full Stack Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Analista de sistemas titulado por la Universidad de Piura'

#sidebar links
email: moises003@gmail.com
phone: +51 941756260
website: moisesjurado.github.io #do not add http://
linkedin: moisesjuradosantos
github: moisesjurado
twitter: '@moisesjurad0'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-109353493-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
